using System;
using System.Collections.Generic;
using System.Text;

namespace FinanceManagement.Uitls
{
    public class AuditLogUtils
    {
        public static Dictionary<string, string> Dict = new Dictionary<string, string>()
        {
            {"Abp.AspNetCore.Mvc.Controllers.AbpUserConfigurationController GetAll"," System "},
            {"FinanceManagement.APIs.Accounts.AccountAppService GetAccountDefault"," Trang Accounts "},
            {"FinanceManagement.APIs.Accounts.AccountAppService GetAll"," Trang Accounts "},
            {"FinanceManagement.APIs.Accounts.AccountAppService GetAllPaging"," Trang Accounts "},
            {"FinanceManagement.APIs.AccountTypes.AccountTypeAppService GetAll"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.AccountTypeAppService GetAllForDropDown"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.AccountTypeAppService GetAllPaging"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.IncomingEntryTypeAppService GetAll"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetAll"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetAllByUserId"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetAllForDropdown"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetAllForDropdownByUser"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetAllForDropdownByUserNew"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetComboxExpenseTypes"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetOutcomingEntryTypeAllByUserId"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService Get"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService GetAll"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService GetAllPaging"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.Banks.BankAppService GetAll"," Trang Quản trị danh mục > Ngân hàng "},
            {"FinanceManagement.APIs.Banks.BankAppService GetAllPaging"," Trang Quản trị danh mục > Ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService Get"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService GetAll"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService GetAllFromBankAccountInTransaction"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService GetAllPaging"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService GetAllToBankAccountInTransaction"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.Branches.BranchAppService GetAll"," Trang Quản trị danh mục > Chi nhánh "},
            {"FinanceManagement.APIs.Branches.BranchAppService GetAllForDropdown"," Trang Quản trị danh mục > Chi nhánh "},
            {"FinanceManagement.APIs.Branches.BranchAppService GetAllPaging"," Trang Quản trị danh mục > Chi nhánh "},
            {"FinanceManagement.APIs.BTransactionLogs.BTransactionLogAppService GetAllPaging"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService GetAllPaging"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService GetCurrentOutcomingSalary"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService GetDefaultToBankAccount"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService GetInfoRollbankOutcomingEntryWithBTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.Comments.CommentAppService GetAllCommentByPost"," Trang Quản lý tài chính > Request chi > Request chi detail "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAccountInRevenues"," GetAccountInRevenues "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllAccounts"," GetAllAccounts "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllAccounTypeEnum"," GetAllAccounTypeEnum "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllBank"," GetAllBank "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllBankAccount"," GetAllBankAccount "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllClient"," GetAllClient "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllCurrency"," GetAllCurrency "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetAllIncomingEntryType"," GetAllIncomingEntryType "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetApprovedOutcomingEntry"," GetApprovedOutcomingEntry "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankAccountByCurrency"," GetBankAccountByCurrency "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankAccountByCurrencyCode"," GetBankAccountByCurrencyCode "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankAccountOptions"," GetBankAccountOptions "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankAccountsInBTransaction"," GetBankAccountsInBTransaction "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankAccountVNDOpstion"," GetBankAccountVNDOpstion "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankAccoutForCompany"," GetBankAccoutForCompany "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBankTransactionFromCompanyByCurrency"," GetBankTransactionFromCompanyByCurrency "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBTransactionOptions"," GetBTransactionOptions "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetBTransactionStatus"," GetBTransactionStatus "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetCommonBankAccountTransactionOpstion"," GetCommonBankAccountTransactionOpstion "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetConversionTransactionDefaultBankAccountByCurrencyId"," GetConversionTransactionDefaultBankAccountByCurrencyId "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetDefaultBankAccountByCurrencyId"," GetDefaultBankAccountByCurrencyId "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetDefaultFromBankAccountByCurrencyIdWhenBuy"," GetDefaultFromBankAccountByCurrencyIdWhenBuy "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetDefaultToBankAccountByCurrencyIdWhenBuy"," GetDefaultToBankAccountByCurrencyIdWhenBuy "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetInvoiceStatuses"," GetInvoiceStatuses "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetOptionTreeOutcomingEntriesByUser"," GetOptionTreeOutcomingEntriesByUser "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetOutcomingEntry"," GetOutcomingEntry "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetRevenueStatuses"," GetRevenueStatuses "},
            {"FinanceManagement.APIs.Commons.CommonAppService GettAllBankAccount"," GettAllBankAccount "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetTreeIncomingEntries"," GetTreeIncomingEntries "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetTreeOutcomingEntries"," GetTreeOutcomingEntries "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService Get"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService GetAll"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService GetAllCurrencyForDropdown"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService GetAllForDropdown"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService GetAllPaging"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService GetAllPaging1"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.CurrenciesConvert.CurrencyConvertAppService GetAllPaging"," Trang Quản trị danh mục > Tỉ giá "},
            {"FinanceManagement.APIs.CurrenciesConvert.CurrencyConvertAppService GetMonthOfCurrencyConvert"," Trang Quản trị danh mục > Tỉ giá "},
            {"FinanceManagement.APIs.CurrenciesConvert.CurrencyConvertAppService GetYearOfCurrencyConvert"," Trang Quản trị danh mục > Tỉ giá "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetBankAccountStatistics"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetCashFlowDashBoard"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetChart"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetComparativeStatisticsOutcomingEntry"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetNewChart"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetPieChartIncoming"," Trang Quản lý tài chính > Đối soát "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetPieChartOutcoming"," Trang Quản lý tài chính > Đối soát "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetReviewExplain"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetStatusDashBoard"," Trang chủ "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService GetAll"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService GetAllByBankTransaction"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService GetAllClient"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService GetAllPaging"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService GetTotalByCurrency"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService Get"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService GetAllPaging"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService GetBankTransactionsByInvoice"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService GetAll"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService GetAllPaging"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService Get"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetAllPaging"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetAllRequester"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetFiles"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetOutcomingEntryMoneyHistoryByOutcomingEntryId"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetOutcomingEntryStatusHistoryByOutcomingEntryId"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetTotalValueOutcomingEntry"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntryBankTransactions.OutcomingEntryBankTransactionAppService GetAllOutcomingEntryByTransaction"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService GetAll"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService GetAllPaging"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService GetTransactionDetails"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.Periods.PeriodAppService GetAll"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.Periods.PeriodAppService GetAllPaging"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.RelationInOutEntrys.RelationInOutEntryAppService GetInByOutId",""},
            {"FinanceManagement.APIs.Suppliers.SupplierAppService GetAll"," Trang Quản trị danh mục > Nhà cung cấp "},
            {"FinanceManagement.APIs.Suppliers.SupplierAppService GetAllByOutcomingEntry"," Trang Quản trị danh mục > Nhà cung cấp "},
            {"FinanceManagement.APIs.Suppliers.SupplierAppService GetAllForDropdown"," Trang Quản trị danh mục > Nhà cung cấp "},
            {"FinanceManagement.APIs.Suppliers.SupplierAppService GetAllPaging"," Trang Admin > Work flow "},
            {"FinanceManagement.APIs.WorkFlows.WorkflowAppService Get"," Trang Admin > Work flow "},
            {"FinanceManagement.APIs.WorkFlows.WorkflowAppService GetAllDropDown"," Trang Admin > Work flow "},
            {"FinanceManagement.APIs.WorkFlows.WorkflowAppService GetAllPaging"," Trang Admin > Work flow "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService GetAll"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService GetAllForDropDown"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService GetAllForDropDownAndNotEqualsEnd"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService GetStatusForOutcomeFilter"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService GetTempOutComingEntryStatusOptions"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkflowStatusTransitions.WorkflowStatusTransitionAppService GetRoleByTransition"," Trang Admin > Trạng thái "},
            {"FinanceManagement.Configuration.ConfigurationAppService Get"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetAllowChangeEntityInPeriodClosed"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetApplyToMultiCurrencyOutcome"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetDefaultLoaiThuIdKhiChiChuyenDoi"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetDefaultMaLoaiMuaNgoaiTe"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetDefaultMaLoaiThuBanNgoaiTe"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetDefaultMaLoaiThuKhachHangBonus"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetDeviantCode"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetEspecialIncomingEntryType"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetOutcomingSalary"," Trang Admin > Cài đặt "},
            {"FinanceManagement.MultiTenancy.TenantAppService GetAllAsync"," Trang > Admin > Công ty "},
            {"FinanceManagement.MultiTenancy.TenantAppService GetAsync"," Trang > Admin > Công ty "},
            {"FinanceManagement.Roles.RoleAppService GetAllAsync"," Trang Admin > Vai trò "},
            {"FinanceManagement.Roles.RoleAppService GetAllPermissions"," Trang Admin > Vai trò "},
            {"FinanceManagement.Roles.RoleAppService GetAllUsersInRole"," Trang Admin > Vai trò "},
            {"FinanceManagement.Roles.RoleAppService GetAllUsersNotInRole"," Trang Admin > Vai trò "},
            {"FinanceManagement.Roles.RoleAppService GetRoleForEdit"," Trang Admin > Vai trò "},
            {"FinanceManagement.Roles.RoleAppService GetRolesAsync"," Trang Admin > Vai trò "},
            {"FinanceManagement.Users.UserAppService GetAllAsync"," Trang Admin > Người dùng "},
            {"FinanceManagement.Users.UserAppService GetAsync"," Trang Admin > Người dùng "},
            {"FinanceManagement.Users.UserAppService GetRoles"," Trang Admin > Người dùng "},
            {"FinanceManagement.APIs.Accounts.AccountAppService Create"," Trang Accounts "},
            {"FinanceManagement.APIs.Accounts.AccountAppService CreateNew"," Trang Accounts "},
            {"FinanceManagement.APIs.AccountTypes.AccountTypeAppService Create"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.IncomingEntryTypeAppService Create"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService Create"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService Create"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.Banks.BankAppService Create"," Trang Quản trị danh mục > Ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService Create"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.Branches.BranchAppService Create"," Trang Quản trị danh mục > Chi nhánh "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CreateBTransactionFromOtherApp"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CreateIncomingEntry"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CreateMultiIncomingEntry"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CreateTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.Comments.CommentAppService CreateCommentByPost"," Trang Quản lý tài chính > Request chi > Request chi detail "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService Create"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.CurrenciesConvert.CurrencyConvertAppService Create"," Trang Quản trị danh mục > Tỉ giá "},
            {"FinanceManagement.APIs.HRMs.HRMAppService CreateOucomingEntryByHRM"," Link to another tool > HRM "},
            {"FinanceManagement.APIs.HRMs.HRMv2AppService CreateOucomingEntryByHRM"," Link to another tool > HRM "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService Create"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService Create"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService CreateInvoice"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService Create"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService Create"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CreateTempOutcomingEntryDetail"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CreateTempOutCommingEntry"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService Create"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.OutcomingEntrySuppliers.OutcomingEntrySupplierAppService Create"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail"},
            {"FinanceManagement.APIs.Periods.PeriodAppService CreateTheFirstTime"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.ProjectManagementApis.ProjectManagementAppService CreateAccount"," Link to another tool > Project "},
            {"FinanceManagement.APIs.ProjectTools.ProjectToolAppService CreateAllInvoices"," Link to another tool > Project "},
            {"FinanceManagement.APIs.RelationInOutEntrys.RelationInOutEntryAppService Create"," Trang quản lý tài chính > Request chi > Request chi detail > Ghi nhận thu "},
            {"FinanceManagement.APIs.Suppliers.SupplierAppService Create"," Trang Quản trị danh mục > Nhà cung cấp "},
            {"FinanceManagement.APIs.TransitionPermissions.TransitionPermissionAppService Create"," Permission "},
            {"FinanceManagement.APIs.WorkFlows.WorkflowAppService Create"," Trang Admin > Work flow "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService Create"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkflowStatusTransitions.WorkflowStatusTransitionAppService Create"," Trang Admin > Trạng thái "},
            {"FinanceManagement.MultiTenancy.TenantAppService CreateAsync"," Trang > Admin > Công ty "},
            {"FinanceManagement.Roles.RoleAppService CreateAsync"," Trang Admin > Vai trò "},
            {"FinanceManagement.Users.UserAppService CreateAsync"," Trang Admin > Người dùng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService Edit"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.Accounts.AccountAppService Delete"," Trang Accounts "},
            {"FinanceManagement.APIs.AccountTypes.AccountTypeAppService Delete"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.IncomingEntryTypeAppService Delete"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService Delete"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService DeleteOutcomingTypeToUser"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService Delete"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.Banks.BankAppService Delete"," Trang Quản trị danh mục > Ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService Delete"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService DeleteFromOutcomingEntry"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.Branches.BranchAppService Delete"," Trang Quản trị danh mục > Chi nhánh "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService Delete"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.Comments.CommentAppService Delete"," Trang Quản lý tài chính > Request chi > Request chi detail "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService Delete"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.CurrenciesConvert.CurrencyConvertAppService Delete"," Trang Quản trị danh mục > Tỉ giá "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService Delete"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService Delete"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService Delete"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService Delete"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService DeleteFile"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService DeleteTempOutcomingEntryDetail"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService Delete"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService DeleteLinkedTransaction"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.APIs.RelationInOutEntrys.RelationInOutEntryAppService Delete"," Trang quản lý tài chính > Request chi > Request chi detail > Ghi nhận thu "},
            {"FinanceManagement.APIs.TransitionPermissions.TransitionPermissionAppService Delete",""},
            {"FinanceManagement.APIs.WorkFlows.WorkflowAppService Delete"," Trang Admin > Work flow "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService Delete"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkflowStatusTransitions.WorkflowStatusTransitionAppService Delete"," Trang Admin > Trạng thái "},
            {"FinanceManagement.MultiTenancy.TenantAppService DeleteAsync"," Trang > Admin > Công ty "},
            {"FinanceManagement.Roles.RoleAppService DeleteAsync"," Trang Admin > Vai trò "},
            {"FinanceManagement.Users.UserAppService DeleteAsync"," Trang Admin > Người dùng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService ExportExcel"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService ExportExcelDetail"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService ExportExcel"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.BankTransactions.BankTransactionAppService NewExportExcel"," Trang Quản lý tài chính > Giao dịch ngân hàng "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService ExportExcel"," Trang chủ "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService ExportExcel"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService ExportExcel"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService ExportPdfById"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService ImportBTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckAccount"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckChiChuyenDoi"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckConversionTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckCreateMultiIncomingEntry"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckDifferentBetweenBankTransAndBTrans"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckMuaNgoaiTe"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.HRMs.HRMv2AppService CheckConnectToHRM"," Trang chủ "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService CheckAutoPaid"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService CheckSetDoneInvoice"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CheckChangeStatus"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CheckExistTempOutCommingEntry"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CheckTempOutcomingEntryApproved"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CheckTempOutCommingEntryHasDetail"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.Periods.PeriodAppService CheckDiffRealBalanceAndBTransaction"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.Public.PublicAppService CheckConnect",""},
            {"FinanceManagement.APIs.Accounts.AccountAppService ChangeStatus"," Trang Accounts "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService ChangeStatus"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService ChangeStatus"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetRequestChangeOutcomingEntry"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService GetRequestChangeOutcomingEntryDetail"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService ViewHistoryChangeOutcomingEntry"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService ChangeDone"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.Configuration.ConfigurationAppService Change"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService ChangeClientAppId"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService ChangeFinanceSecretKey"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService ChangeRequestChiSetting"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService ChangeNotifyKomuChannel"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Roles.RoleAppService ChangeRolePermission"," Trang Admin > Vai trò "},
            {"FinanceManagement.APIs.AccountTypes.IncomingEntryTypeAppService GetExistInComeInChartSetting"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetAllForLinechartSetting"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService GetExistOutComeInChartSetting"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService SetDefaultCurrency"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService SetDefaultFromBankAccountIdWhenBuy"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService SetDefaultToBankAccountIdWhenBuy"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService SetClientPayDeviant"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService SetDoneInvoice"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetApplyToMultiCurrencyOutcome"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetDefaultMaLoaiMuaNgoaiTe"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetDefaultMaLoaiThuBanNgoaiTe"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetEspecialIncomingEntryType"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetOutcomingSalary"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Users.UserAppService ResetPassword"," Trang Admin > Người dùng "},
            {"FinanceManagement.Configuration.ConfigurationAppService ClearDefaultMaLoaiMuaNgoaiTe"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService ClearDefaultMaLoaiThuBanNgoaiTe"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService ClearDefaultToBankAccount"," Trang Admin > Cài đặt "},
            {"FinanceManagement.APIs.Accounts.AccountAppService Update"," Trang Accounts "},
            {"FinanceManagement.APIs.AccountTypes.AccountTypeAppService Update"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.IncomingEntryTypeAppService Update"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService Update"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.BankAccounts.BankAccountAppService Update"," Trang Quản lý tài khoản > Tài khoản ngân hàng "},
            {"FinanceManagement.APIs.Banks.BankAppService Update"," Trang Quản trị danh mục > Ngân hàng "},
            {"FinanceManagement.APIs.Branches.BranchAppService Update"," Trang Quản trị danh mục > Chi nhánh "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService UpdateTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.Comments.CommentAppService UpdateCommentByPost"," Trang Quản lý tài chính > Request chi > Request chi detail "},
            {"FinanceManagement.APIs.Curencies.CurrencyAppService Update"," Trang Quản trị danh mục > Tiền tệ "},
            {"FinanceManagement.APIs.CurrenciesConvert.CurrencyConvertAppService Update"," Trang Quản trị danh mục > Tỉ giá "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService Update"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.IncomingEntries.IncomingEntryAppService UpdateIcomeType"," Trang Quản lý tài chính > Ghi nhận thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService Update"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService UpdateInvoice"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService UpdateNote"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.Invoices.InvoiceAppService UpdateStatus"," Trang Quản lý tài chính > Khoản phải thu "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService Update"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService Update"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService UpdateOutcomingEntryType"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService UpdateReportDate"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService UpdateTempOutcomingEntryDetail"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService Update"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.Periods.PeriodAppService Update"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.WorkFlowStatuses.WorkflowStatusAppService Update"," Trang Admin > Trạng thái "},
            {"FinanceManagement.APIs.WorkflowStatusTransitions.WorkflowStatusTransitionAppService Update"," Trang Admin > Trạng thái "},
            {"FinanceManagement.MultiTenancy.TenantAppService UpdateAsync"," Trang > Admin > Công ty "},
            {"FinanceManagement.Roles.RoleAppService UpdateAsync"," Trang Admin > Vai trò "},
            {"FinanceManagement.Users.UserAppService UpdateAsync"," Trang Admin > Người dùng "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService ComparativeStatistics"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetComparativeStatisticByCurrency"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetComparativeStatisticsIncomingEntry"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService GetComparativeStatisticsOutBankTransaction"," Trang chủ "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService AddAllOutcomingTypeToUser"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.AccountTypes.OutcomingEntryTypeAppService AddOutcomingTypeToUser"," Trang Quản trị danh mục > Loại đối tượng "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService AddReviewExplain"," Trang chủ "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService AddReferenceToLineChart"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService AddBankTransaction"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.Roles.RoleAppService AddUserIntoRole"," Trang Admin > Vai trò "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService PercentEntryType"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService OverviewBTransactionStatistics"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService OverviewInvoiceStatistics"," Trang chủ "},
            {"FinanceManagement.APIs.DashBoards.DashBoardAppService OverviewOutcomingEntryStatistics"," Trang chủ "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService Active"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService DeActive"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.LineChartSettings.LineChartSettingAppService RemoveLineChartReference"," Trang Admin > Chart setting "},
            {"FinanceManagement.APIs.OutcomingEntrySuppliers.OutcomingEntrySupplierAppService RemoveSupplierFromOutcomingEntry"," Trang quản lý tài chính > Request chi > Xoá nhà cung cấp"},
            {"FinanceManagement.Roles.RoleAppService RemoveUserFromRole"," Trang Admin > Vai trò "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService SaveTempOutCommingEntry"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntryBankTransactions.OutcomingEntryBankTransactionAppService SaveMultipleRequest"," Trang Quản lý tài chính > Request chi > Request chi detail"},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService SendTemp"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService RejectTemp"," RejectTemp "},
            {"FinanceManagement.APIs.Commons.CommonAppService GetApprovedAndEndOutcomingEntry"," GetApprovedAndEndOutcomingEntry "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService ApproveTemp"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService ViewHistoryChangeOutcomingEntryDetail"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.Periods.PeriodAppService PreviewBeforeWhenClosePeriod"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService RevertTempOutcomingDetailByRootId"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService RemindCEO"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService RemindCEORequestChange"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService UploadFile"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService CloneOutcomingEntryhoten"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.OutcomingEntries.OutcomingEntryAppService AcceptFile"," Trang Quản lý tài chính > Request chi "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService CheckCurrencyLinkOutcomingEntryWithBTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService LinkBankTransactionToBTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService LinkMultipleOutcomingEntryWithBTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService LinkOutcomingEntrySalaryWithBTransactions"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.BTransactions.BTransactionAppService LinkOutcomingEntryWithBTransaction"," Trang Quản lý tài chính > Biến động số dư "},
            {"FinanceManagement.APIs.OutcomingEntryDetails.OutcomingEntryDetailAppService LinkToExistingTransaction"," Trang Quản lý tài chính > Request chi > OutcomingEntryDetail "},
            {"FinanceManagement.Configuration.ConfigurationAppService GetCanLinkWithOutcomingEnd"," Trang Admin > Cài đặt "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetCanLinkWithOutcomingEnd"," Trang Admin > Cài đặt "},
            {"FinanceManagement.APIs.Periods.PeriodAppService CloseAndCreatePeriod"," Trang Quản lý tài chính > Kỳ kế toán "},
            {"FinanceManagement.Configuration.ConfigurationAppService SetAllowChangeEntityInPeriodClosed"," Trang Admin > Cài đặt "},
            {"FinanceManagement.APIs.Auditlog.AuditLogAppService GetAllEmailAddressInAuditLog"," Trang Admin > Auditlog "},
            {"FinanceManagement.APIs.Auditlog.AuditLogAppService GetAllPagging"," Trang Admin > Auditlog "},
            {"FinanceManagement.Controllers.TokenAuthController Authenticate"," Login "},
            {"FinanceManagement.Web.Host.Controllers.AntiForgeryController SetCookie"," SetCookie "},
            {"FinanceManagement.Web.Host.Controllers.HomeController Index"," Index "},
            {"FinanceManagement.APIs.Periods.PeriodAppService IsTheFirstRecord"," Trang Quản lý tài chính > Kỳ kế toán "},

        };
        public static string GetNote(string serviceName, string methodName)
        {
           return Dict.ContainsKey(serviceName + " " + methodName) ? Dict[serviceName + " " + methodName] : "";
        }
    }
}
